### ISSUE TITLE
Unable to generate MOF

### ISSUE THREAD

**Issue by electricJP** [PowerShell/WmiNamespaceSecurity#1]
Hello,

Trying to use this resource in a configuration file:

WMINamespaceSecurity srv_acc_tst
        {
            Path = "root/cimv2"
            Principal = "contoso\srv_acc_tst"
            AppliesTo = "Self"
            AccessType = "Allow"
            Permission = "Enable","MethodExecute"
            Ensure = "Present"
        }

I get this error:

Write-NodeMOFFile : Invalid MOF definition for node 'server.conto.org': Exception calling "ValidateInstanceText" with "1" argument(s): "Convert property 'Permission' value from type 'STRING[]' to type 'STRING' failed
 At line:46, char:2
 Buffer:
e = "My_Config";
};^
insta
"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2275 char:21
- ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
  - FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile

Removing the above section allows the MOF generation.

Any idea? I would really need to use this resource to ease my work.
Thank you.

JP

**Comment by SteveL-MSFT** [comment]
@electricJP sorry for not monitoring this repo, but I've pushed a fix for this.  Apparently a change in DSC broke this resourece as an enum array isn't supported, so I changed it to a string array.

**Comment by SandeshT19** [comment]
Hi I Am still facing same issue ,but did not get the fix ..
