### ISSUE TITLE
Local Group

### ISSUE THREAD

**Issue by rdavisunr** [PowerShell/WmiNamespaceSecurity#2]
Hello

I am using the resource as follows:

```
WMINamespaceSecurity PerformanceLogUsers {
    Path = "root/cimv2"
    Principal = ".\Performance Log Users"
    AppliesTo = "Self"
    AccessType = "Allow"
    Permission = "Enable", "RemoteAccess"
    PsDscRunAsCredential = $DomainAdminCreds
    Ensure = "Present"
}
```

With these values, the configuration completes successfully and the "Performance Log Users" group ends up being added with the correct permissions (as shown here):

![performancelogusers](https://user-images.githubusercontent.com/8481440/37855539-f2373306-2eac-11e8-897c-84f33dc330b8.PNG)

However, Test-DscConfiguration returns false. When I pass the -Detailed flag, Test-DscConfiguration confirms the Resource is not in the desired state. I believe this is because the trustee domain is actually "BUILTIN" (not "."), so the ACE cannot be located by the FindAce method.

This led me to try setting the Principal to "BUILTIN\Performance Log Users", however that results in a failure when trying to initially apply the configuration. The issue seems to be with the following block:
```powershell
$domain, $user = [WMINamespaceSecurity]::SplitPrincipal($this.Principal)
 if ($domain -eq [string]::Empty -or $domain -eq "BUILTIN") {
    $domain = $env:COMPUTERNAME
 }
$ntuser = New-Object System.Security.Principal.NTAccount($domain,$user)
$trustee = New-CimInstance -Namespace root/cimv2 -ClassName Win32_Trustee -ClientOnly -Property @{Domain=$domain;Name=$user;
    SidString=$ntuser.Translate([System.Security.Principal.SecurityIdentifier]).Value}
```
The error I get looks similar to the following:
![error](https://user-images.githubusercontent.com/8481440/37855766-2e024dc0-2eae-11e8-9a4a-c968998a1b68.PNG)

The IF block in that snippet replaces a domain set to "BUILTIN" with $env:COMPUTERNAME. However, that causes the above exception on my machine.

Any advice or thoughts on this would be most appreciated...

**Comment by rdavisunr** [comment]
Just wanted to add that Test-DscConfiguration fails for domain accounts as well (not just local groups). In this case, I think FindAce is working fine, but the logic in the Test() method looks incorrect to me...

```powershell
[bool] Test() {
    $wmiNamespace = $this.Get()
    if ($this.Ensure -eq [Ensure]::Absent -and $wmiNamespace -eq $null)
    {
        return $true
    } else {
        return $false
    }
}
```
That above logic means the resource will only be in the desired state when setting it to absent? It seems like there is a case missing which would return true when the resource has been succesfully configured. Something like this...
```powershell
[bool] Test() {
    $wmiNamespace = $this.Get()
    if ($this.Ensure -eq [Ensure]::Absent -and $wmiNamespace -eq $null)
    {
        return $true
    } elseif ($this.Ensure -eq [Ensure]::Present -and $wmiNamespace -ne $null) {
        return $true
    }
    else
    {
        return $false
    }
```

Thoughts @SteveL-MSFT , @SteveL-PowerShell ?

**Comment by SteveL-MSFT** [comment]
@rdavisunr I believe you are correct.  Can you submit as a PR?

**Comment by rdavisunr** [comment]
@SteveL-MSFT 

Sorry, just getting back around to this.. 

I assume you mean submit a PR for the issue with the Test() method? 

Do you have any feedback on the other issue I described in the first message in the thread?

Specifically, do you agree there is an issue with the Set() method? Do you recall why the code transforms a domain equal to "BUILTIN" into $env:COMPUTERNAME? If Domain is set to $env:COMPUTERNAME I get the following exception when the config is applied:
``` powershell
Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."
At line:7 char:1
+ $trustee = New-CimInstance -Namespace root/cimv2 -ClassName Win32_Tru ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException
```

In my case, removing that conversion (and updating the Test() method) allows both the config and the test to succeed (at least when I set **Principal = "BUILTIN\Performance Log Users"**).

**Comment by SteveL-MSFT** [comment]
@rdavisunr this code is so old, I don't recall why some of the decisions were made.  I don't have plans to support this, but welcome community support.

**Comment by SteveL-MSFT** [comment]
Closing this based on your PR.  Will publish updated version to PSGallery.  Thanks!

**Comment by SteveL-MSFT** [comment]
https://www.powershellgallery.com/packages/WmiNamespaceSecurity/0.3.0
